# Generated by Django 3.2.25 on 2026-09-21 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start_date'], 'verbose_name': 'конференция', 'verbose_name_plural': 'конференции'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'регистрация', 'verbose_name_plural': 'регистрации'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'тематика', 'verbose_name_plural': 'тематики'},
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='participation_terms',
            field=models.TextField(blank=True, verbose_name='условия участия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='conferences', to='conferences.Topic', verbose_name='тематики'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue_description',
            field=models.TextField(blank=True, verbose_name='описание места проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue_name',
            field=models.CharField(max_length=200, verbose_name='место проведения'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference', verbose_name='конференция'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='recommended_for_publication',
            field=models.BooleanField(blank=True, null=True, verbose_name='рекомендован к публикации'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='talk_title',
            field=models.CharField(max_length=200, verbose_name='тема доклада'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conferences.conference', verbose_name='конференция'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
